# Generated by Django 5.1.5 on 2026-04-25 03:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0004_student_allergies_student_dietary_notes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BehaviourEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('merit', 'Merit — keep doing this'), ('demerit', 'Demerit — gentle correction'), ('note', 'Pastoral note')], default='merit', max_length=10)),
                ('points', models.IntegerField(default=1)),
                ('title', models.CharField(max_length=120)),
                ('detail', models.TextField(blank=True)),
                ('is_visible_to_parent', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behaviour_entries', to='academics.student')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='behaviour_entries', to='academics.teacher')),
                ('term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='behaviour_entries', to='academics.term')),
            ],
            options={
                'verbose_name_plural': 'Behaviour entries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HealthLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visited_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('complaint', models.CharField(max_length=200)),
                ('action_taken', models.CharField(blank=True, max_length=300)),
                ('severity', models.CharField(choices=[('minor', 'Minor — observed and treated'), ('moderate', 'Moderate — guardian informed'), ('serious', 'Serious — sent home / referred')], default='minor', max_length=20)),
                ('sent_home', models.BooleanField(default=False)),
                ('guardian_notified', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('nurse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_logs', to='academics.student')),
            ],
            options={
                'ordering': ['-visited_at'],
            },
        ),
        migrations.CreateModel(
            name='SchoolEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('starts_at', models.TimeField(blank=True, null=True)),
                ('ends_at', models.TimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('kind', models.CharField(choices=[('holiday', 'Holiday'), ('term_start', 'Term begins'), ('term_end', 'Term ends'), ('midterm', 'Mid-term break'), ('exam', 'Exam / assessment'), ('ptm', 'Parent–teacher meeting'), ('sports', 'Sports / inter-house'), ('cultural', 'Cultural / arts day'), ('trip', 'Excursion'), ('closure', 'Emergency closure'), ('other', 'Other')], default='other', max_length=20)),
                ('audience', models.CharField(choices=[('all', 'Everyone'), ('staff', 'Staff only'), ('parents', 'Parents + staff'), ('nursery', 'Nursery section only'), ('basic', 'Basic section only')], default='all', max_length=20)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['start_date', 'starts_at'],
            },
        ),
    ]
