# Generated by Django 5.1.5 on 2026-04-25 03:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_student_allergies_student_dietary_notes_and_more'),
        ('wellbeing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentBankEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('band', models.CharField(choices=[('excellent', 'Excellent (A)'), ('good', 'Good (B)'), ('average', 'Average (C/D)'), ('below', 'Below average (E/F)'), ('effort', 'Effort note'), ('behaviour', 'Behaviour note')], default='good', max_length=20)),
                ('text', models.TextField()),
                ('times_used', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contributed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(blank=True, help_text='Leave blank for cross-subject behaviour/effort comments.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_bank', to='academics.subject')),
            ],
            options={
                'ordering': ['-times_used', 'subject', 'band'],
            },
        ),
        migrations.CreateModel(
            name='CurriculumStrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('week_number', models.PositiveIntegerField(blank=True, help_text='Week 1-13 of term.', null=True)),
                ('is_covered', models.BooleanField(default=False)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_strands', to='academics.classlevel')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_strands', to='academics.subject')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_strands', to='academics.term')),
            ],
            options={
                'ordering': ['term', 'class_level', 'subject', 'week_number'],
            },
        ),
        migrations.CreateModel(
            name='DrillLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('fire', 'Fire drill'), ('lockdown', 'Lockdown drill'), ('evacuation', 'Evacuation')], default='fire', max_length=20)),
                ('held_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, help_text='Time-to-evacuate / drill duration.', null=True)),
                ('pupils_count', models.PositiveIntegerField(blank=True, null=True)),
                ('staff_count', models.PositiveIntegerField(blank=True, null=True)),
                ('observations', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('led_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-held_at'],
            },
        ),
        migrations.CreateModel(
            name='PupilBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='e.g. "reader-10", "kindness", "sports-day"', max_length=40)),
                ('label', models.CharField(max_length=120)),
                ('icon', models.CharField(default='🏅', help_text='Emoji / single character.', max_length=10)),
                ('awarded_on', models.DateField(default=django.utils.timezone.localdate)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('awarded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to='academics.student')),
            ],
            options={
                'ordering': ['-awarded_on'],
            },
        ),
        migrations.CreateModel(
            name='SafeguardingIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(max_length=200)),
                ('detail', models.TextField()),
                ('severity', models.CharField(choices=[('info', 'Information / context'), ('low', 'Low — monitor'), ('medium', 'Medium — investigate'), ('high', 'High — immediate action')], default='low', max_length=10)),
                ('status', models.CharField(choices=[('filed', 'Filed'), ('triaged', 'Triaged by DSL'), ('in_progress', 'Action in progress'), ('closed', 'Closed')], default='filed', max_length=20)),
                ('triage_note', models.TextField(blank=True)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('filed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(blank=True, help_text='Optional — some incidents are about adults.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='safeguarding_incidents', to='academics.student')),
                ('triaged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Safeguarding incident',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StaffCertification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g. "First Aid (FAA)", "Child Protection"', max_length=120)),
                ('issuer', models.CharField(blank=True, max_length=120)),
                ('issued_on', models.DateField()),
                ('expires_on', models.DateField(blank=True, null=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='certifications/')),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['expires_on'],
            },
        ),
        migrations.CreateModel(
            name='MoodPulse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood', models.CharField(choices=[('great', '😄 Great'), ('ok', '🙂 OK'), ('meh', '😐 Meh'), ('sad', '😞 Sad'), ('worried', '😟 Worried')], default='ok', max_length=10)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('pulsed_on', models.DateField(default=django.utils.timezone.localdate)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('captured_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mood_pulses', to='academics.student')),
            ],
            options={
                'ordering': ['-pulsed_on'],
                'unique_together': {('student', 'pulsed_on')},
            },
        ),
        migrations.CreateModel(
            name='PolicyAcknowledgement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy', models.CharField(choices=[('safeguarding', 'Safeguarding'), ('data_protection', 'Data Protection'), ('code_of_conduct', 'Staff Code of Conduct'), ('anti_bullying', 'Anti-bullying'), ('acceptable_use', 'Acceptable Use of ICT')], max_length=30)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('acknowledged_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ip', models.CharField(blank=True, max_length=45)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policy_acks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-acknowledged_at'],
                'unique_together': {('user', 'policy', 'version')},
            },
        ),
        migrations.CreateModel(
            name='ReadingLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J'), ('K', 'K'), ('L', 'L'), ('M', 'M'), ('N', 'N'), ('O', 'O'), ('P', 'P')], help_text='Fountas & Pinnell-style level.', max_length=2)),
                ('fluency_wpm', models.PositiveIntegerField(blank=True, help_text='Oral reading fluency, words/min.', null=True)),
                ('note', models.TextField(blank=True)),
                ('assessed_on', models.DateField(default=django.utils.timezone.localdate)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_levels', to='academics.student')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='academics.teacher')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_levels', to='academics.term')),
            ],
            options={
                'ordering': ['-assessed_on'],
                'unique_together': {('student', 'term')},
            },
        ),
    ]
