# Generated by Django 5.1.5 on 2026-09-23 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wellbeing', '0002_commentbankentry_curriculumstrand_drilllog_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolevent',
            name='audience',
            field=models.CharField(choices=[('all', 'Everyone'), ('staff', 'Staff only'), ('parents', 'Parents + staff'), ('kg', 'KG section only'), ('nursery', 'Nursery section only'), ('basic', 'Primary section only')], default='all', max_length=20),
        ),
    ]
