# Generated by Django 5.1.5 on 2026-04-25 03:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0004_student_allergies_student_dietary_notes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(blank=True, max_length=200)),
                ('isbn', models.CharField(blank=True, max_length=20)),
                ('section', models.CharField(choices=[('nursery', 'Nursery'), ('basic', 'Basic'), ('staff', 'Staff')], default='basic', max_length=10)),
                ('copies_total', models.PositiveIntegerField(default=1)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='books/')),
                ('note', models.CharField(blank=True, max_length=200)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='BusRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. "Mowe → Ibafo loop"', max_length=80)),
                ('driver_name', models.CharField(blank=True, max_length=120)),
                ('driver_phone', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BookLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrowed_on', models.DateField(default=django.utils.timezone.localdate)),
                ('due_on', models.DateField()),
                ('returned_on', models.DateField(blank=True, null=True)),
                ('fine', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='operations.book')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_loans', to='academics.student')),
            ],
            options={
                'ordering': ['-borrowed_on'],
            },
        ),
        migrations.CreateModel(
            name='BusStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('order', models.PositiveIntegerField(default=0, help_text='Pickup order, low → high.')),
                ('pickup_time', models.TimeField(blank=True, null=True)),
                ('dropoff_time', models.TimeField(blank=True, null=True)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='operations.busroute')),
            ],
            options={
                'ordering': ['route', 'order'],
            },
        ),
        migrations.CreateModel(
            name='BusRiderAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bus_assignment', to='academics.student')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='riders', to='operations.busroute')),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='riders', to='operations.busstop')),
            ],
        ),
        migrations.CreateModel(
            name='BusCheckpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('departed', 'Departed school'), ('approaching', 'Approaching stop'), ('at_stop', 'At stop'), ('completed', 'Route completed'), ('incident', 'Incident — see note')], default='departed', max_length=20)),
                ('pinged_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pinged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkpoints', to='operations.busroute')),
                ('stop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkpoints', to='operations.busstop')),
            ],
            options={
                'ordering': ['-pinged_at'],
            },
        ),
        migrations.CreateModel(
            name='LateCheckout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logged_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('collected_at', models.DateTimeField(blank=True, null=True)),
                ('collected_by', models.CharField(blank=True, help_text='Name / relationship of who finally collected the child.', max_length=120)),
                ('status', models.CharField(choices=[('waiting', 'Still waiting'), ('collected', 'Collected'), ('escalated', 'Escalated to office')], default='waiting', max_length=10)),
                ('guardian_notified', models.BooleanField(default=False)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('logged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='late_checkouts', to='academics.student')),
            ],
            options={
                'ordering': ['-logged_at'],
            },
        ),
        migrations.CreateModel(
            name='LostFoundItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text='e.g. "blue water bottle with stickers"', max_length=200)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='lost-found/')),
                ('found_on', models.DateField(default=django.utils.timezone.localdate)),
                ('found_at', models.CharField(blank=True, help_text='Where it was found.', max_length=120)),
                ('status', models.CharField(choices=[('found', 'Found — awaiting claim'), ('claimed', 'Claimed'), ('disposed', 'Disposed / donated')], default='found', max_length=10)),
                ('claimed_by', models.CharField(blank=True, help_text='Name of guardian / pupil who collected.', max_length=120)),
                ('claimed_on', models.DateField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('class_level', models.ForeignKey(blank=True, help_text='Likely class, if known.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='academics.classlevel')),
            ],
            options={
                'verbose_name': 'Lost & found item',
                'ordering': ['-found_on', '-created_at'],
            },
        ),
    ]
