# Generated by Django 5.1.5 on 2026-04-25 03:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_student_allergies_student_dietary_notes_and_more'),
        ('operations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('description', models.TextField(blank=True)),
                ('schedule', models.CharField(blank=True, help_text='e.g. "Mon & Wed 3-4pm"', max_length=120)),
                ('capacity', models.PositiveIntegerField(default=20)),
                ('fee_naira', models.DecimalField(decimal_places=2, default=0, help_text='Per term. 0 = free.', max_digits=10)),
                ('section', models.CharField(blank=True, choices=[('nursery', 'Nursery'), ('basic', 'Basic')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FundraisingCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('blurb', models.TextField(blank=True)),
                ('goal_naira', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('raised_naira', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='fundraising/')),
                ('starts_on', models.DateField(default=django.utils.timezone.localdate)),
                ('ends_on', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-starts_on'],
            },
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_name', models.CharField(max_length=120)),
                ('donor_email', models.EmailField(blank=True, max_length=254)),
                ('donor_phone', models.CharField(blank=True, max_length=20)),
                ('amount_naira', models.DecimalField(decimal_places=2, max_digits=12)),
                ('method', models.CharField(default='transfer', max_length=20)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('given_on', models.DateField(default=django.utils.timezone.localdate)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='operations.fundraisingcampaign')),
            ],
            options={
                'ordering': ['-given_on'],
            },
        ),
        migrations.CreateModel(
            name='GeneratorFuelLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('diesel', 'Diesel'), ('petrol', 'Petrol'), ('solar_service', 'Solar service')], default='diesel', max_length=20)),
                ('litres', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('cost_naira', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('hours_run', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('purchased_on', models.DateField(default=django.utils.timezone.localdate)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('logged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-purchased_on'],
            },
        ),
        migrations.CreateModel(
            name='OutageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('power', 'Power outage'), ('internet', 'Internet outage'), ('water', 'Water'), ('other', 'Other')], default='power', max_length=20)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('impact_note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('logged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ClubBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending payment'), ('confirmed', 'Confirmed'), ('waitlist', 'Waitlist'), ('cancelled', 'Cancelled')], default='pending', max_length=10)),
                ('booked_on', models.DateField(default=django.utils.timezone.localdate)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='operations.club')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_bookings', to='academics.student')),
            ],
            options={
                'ordering': ['-booked_on'],
                'unique_together': {('club', 'student')},
            },
        ),
    ]
