# Generated by Django 5.1.5 on 2026-09-23 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_club_fundraisingcampaign_donation_generatorfuellog_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='section',
            field=models.CharField(choices=[('kg', 'KG'), ('nursery', 'Nursery'), ('basic', 'Primary'), ('staff', 'Staff')], default='basic', max_length=10),
        ),
        migrations.AlterField(
            model_name='club',
            name='section',
            field=models.CharField(blank=True, choices=[('kg', 'KG'), ('nursery', 'Nursery'), ('basic', 'Primary')], max_length=10),
        ),
    ]
