# Generated by Django 5.1.5 on 2026-04-24 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_attendancerecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasicGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ca1', models.PositiveSmallIntegerField(default=0, help_text='0–20')),
                ('ca2', models.PositiveSmallIntegerField(default=0, help_text='0–20')),
                ('exam', models.PositiveSmallIntegerField(default=0, help_text='0–60')),
                ('total', models.PositiveSmallIntegerField(default=0)),
                ('grade', models.CharField(blank=True, max_length=2)),
                ('remark', models.CharField(blank=True, max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basic_grades', to='academics.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grades', to='academics.subject')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grades_entered', to='academics.teacher')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='basic_grades', to='academics.term')),
            ],
            options={
                'ordering': ['student__last_name', 'subject__name'],
                'unique_together': {('student', 'subject', 'term')},
            },
        ),
        migrations.CreateModel(
            name='NurseryAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(choices=[('literacy', 'Literacy Readiness'), ('numeracy', 'Numeracy Readiness'), ('social', 'Social Development'), ('emotional', 'Emotional Development'), ('motor', 'Motor Skills'), ('creative', 'Creative Arts'), ('participation', 'Class Participation'), ('behavior', 'Behaviour')], max_length=20)),
                ('rating', models.CharField(choices=[('E', 'Excellent'), ('VG', 'Very Good'), ('G', 'Good'), ('F', 'Fair'), ('NI', 'Needs Improvement')], default='G', max_length=3)),
                ('remark', models.CharField(blank=True, max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nursery_assessments', to='academics.student')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments_entered', to='academics.teacher')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nursery_assessments', to='academics.term')),
            ],
            options={
                'ordering': ['student__last_name', 'domain'],
                'unique_together': {('student', 'term', 'domain')},
            },
        ),
    ]
