# Generated by Django 5.1.5 on 2026-04-25 02:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_basicgrade_nurseryassessment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='allergies',
            field=models.TextField(blank=True, help_text="e.g. 'Peanuts (severe), shellfish'"),
        ),
        migrations.AddField(
            model_name='student',
            name='dietary_notes',
            field=models.TextField(blank=True, help_text='Vegetarian, halal, lactose intolerant…'),
        ),
        migrations.AddField(
            model_name='student',
            name='medical_notes',
            field=models.TextField(blank=True, help_text='Asthma, on-going medication, etc.'),
        ),
        migrations.CreateModel(
            name='PickupAuthorization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('relationship', models.CharField(choices=[('parent', 'Parent'), ('guardian', 'Guardian'), ('relative', 'Relative'), ('driver', 'Driver'), ('nanny', 'Nanny / minder'), ('family_friend', 'Family friend'), ('other', 'Other')], default='parent', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='pickup-auths/')),
                ('id_note', models.CharField(blank=True, help_text="e.g. 'NIN ending 4823' or 'driver's licence on file'", max_length=120)),
                ('valid_from', models.DateField(blank=True, help_text='Leave blank for an ongoing pass', null=True)),
                ('valid_until', models.DateField(blank=True, help_text='Leave blank for an ongoing pass', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pickup_auths_added', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_auths', to='academics.student')),
            ],
            options={
                'ordering': ['student__last_name', 'name'],
            },
        ),
    ]
