# Generated by Django 5.1.5 on 2026-07-06 23:12

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_alter_student_enrollment_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classlevel',
            options={'base_manager_name': 'all_objects', 'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'base_manager_name': 'all_objects', 'ordering': ['class_level__order', 'last_name', 'first_name']},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'base_manager_name': 'all_objects', 'ordering': ['section', 'name']},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'base_manager_name': 'all_objects', 'ordering': ['last_name', 'first_name']},
        ),
        migrations.AlterModelManagers(
            name='classlevel',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='student',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='subject',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='teacher',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='classlevel',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='classlevel',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subject',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teacher',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
