# Generated by Django 5.1.5 on 2026-07-06 23:48

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_alter_classlevel_options_alter_student_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guardian',
            options={'base_manager_name': 'all_objects', 'ordering': ['last_name', 'first_name']},
        ),
        migrations.AlterModelManagers(
            name='guardian',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='guardian',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guardian',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
