# Generated by Django 5.1.5 on 2026-07-07 17:38

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_alter_guardian_options_alter_guardian_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basicgrade',
            options={'base_manager_name': 'all_objects', 'ordering': ['student__last_name', 'subject__name']},
        ),
        migrations.AlterModelOptions(
            name='nurseryassessment',
            options={'base_manager_name': 'all_objects', 'ordering': ['student__last_name', 'domain']},
        ),
        migrations.AlterModelManagers(
            name='basicgrade',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='nurseryassessment',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='basicgrade',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basicgrade',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='nurseryassessment',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nurseryassessment',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
