# Generated by Django 5.1.5 on 2026-09-19 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0008_alter_basicgrade_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicgrade',
            name='teacher_comment',
            field=models.TextField(blank=True, help_text='Custom comment for the report card'),
        ),
    ]
