# Generated by Django 5.1.5 on 2026-09-23 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0010_add_kg_section_update_class_levels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classlevel',
            name='order',
            field=models.PositiveSmallIntegerField(help_text='Display order', unique=True),
        ),
        migrations.AlterField(
            model_name='classlevel',
            name='section',
            field=models.CharField(choices=[('kg', 'Kindergarten'), ('nursery', 'Nursery'), ('basic', 'Primary')], max_length=10),
        ),
        migrations.AlterField(
            model_name='subject',
            name='section',
            field=models.CharField(choices=[('kg', 'Kindergarten'), ('nursery', 'Nursery'), ('basic', 'Primary')], max_length=10),
        ),
    ]
