# Generated by Django 5.1.5 on 2026-07-07 19:13

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_paymentplan_paymentplaninstalment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feeschedule',
            options={'base_manager_name': 'all_objects', 'ordering': ['term__start_date', 'class_level__order', 'name']},
        ),
        migrations.AlterModelOptions(
            name='invoice',
            options={'base_manager_name': 'all_objects', 'ordering': ['-issued_on']},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'base_manager_name': 'all_objects', 'ordering': ['-received_on', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='paymentplan',
            options={'base_manager_name': 'all_objects', 'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='paymentplaninstalment',
            options={'base_manager_name': 'all_objects', 'ordering': ['sequence']},
        ),
        migrations.AlterModelManagers(
            name='feeschedule',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='invoice',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='payment',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='paymentplan',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='paymentplaninstalment',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='feeschedule',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feeschedule',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoice',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payment',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paymentplan',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentplan',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paymentplaninstalment',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentplaninstalment',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
