# Generated by Django 5.1.5 on 2026-09-21 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0009_add_teacher_comment'),
        ('finance', '0003_alter_feeschedule_options_alter_invoice_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('nursery', 'Nursery / KG'), ('basic', 'Primary')], max_length=10)),
                ('name', models.CharField(help_text='e.g. "Mathematics", "Notebook 20pcs"', max_length=150)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('note', models.CharField(blank=True, help_text='e.g. "@₦600 each"', max_length=200)),
                ('sn', models.PositiveIntegerField(default=0, help_text='Serial number for ordering')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['section', 'sn', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BillItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. "School Fee", "Uniform"', max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sn', models.PositiveIntegerField(default=0, help_text='Serial number for ordering')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('class_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_items', to='academics.classlevel')),
            ],
            options={
                'ordering': ['class_level__order', 'sn', 'name'],
                'unique_together': {('class_level', 'name')},
            },
        ),
    ]
