# Generated by Django 6.0.1 on 2026-01-17 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_admission'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(help_text='Unique Student ID or Reg Number', max_length=50)),
                ('student_name', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=100)),
                ('score', models.IntegerField()),
                ('grade', models.CharField(max_length=2)),
                ('term', models.CharField(default='First Term', max_length=50)),
                ('session', models.CharField(default='2025/2026', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='admission',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10),
        ),
        migrations.AlterField(
            model_name='admission',
            name='previous_school',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
