# Generated by Django 6.0.1 on 2026-01-17 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_studentresult_alter_admission_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='student_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
