# Generated by Django 6.0.1 on 2026-01-17 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_admission_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='passport_photo',
            field=models.ImageField(blank=True, null=True, upload_to='passports/'),
        ),
    ]
