# Generated by Django 6.0.1 on 2026-01-17 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_admission_passport_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentresult',
            name='student_class',
            field=models.CharField(default='JSS 1', max_length=50),
        ),
    ]
