# Generated by Django 6.0.1 on 2026-01-17 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_studentresult_student_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentresult',
            name='student_class',
            field=models.CharField(default='Nursery 1', max_length=50),
        ),
    ]
