# Generated by Django 5.1.5 on 2026-04-25 03:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_admission_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_name', models.CharField(max_length=200)),
                ('parent_phone', models.CharField(max_length=20)),
                ('parent_email', models.EmailField(blank=True, max_length=254)),
                ('children_count', models.PositiveIntegerField(default=1)),
                ('interest_class', models.CharField(blank=True, help_text='e.g. "Nursery 1", "Basic 3"', max_length=50)),
                ('requested_date', models.DateField()),
                ('requested_slot', models.CharField(default='10:00', help_text='e.g. "10:00" or "14:30"', max_length=20)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No-show')], default='requested', max_length=20)),
                ('note', models.TextField(blank=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-requested_date'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('applied', 'Applied'), ('assessed', 'Assessment scheduled'), ('offered', 'Offered place'), ('accepted', 'Place accepted'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn by family'), ('enrolled', 'Enrolled (now a student)')], default='applied', max_length=20)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('happened_at', models.DateTimeField(auto_now_add=True)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='core.admission')),
            ],
            options={
                'ordering': ['happened_at'],
            },
        ),
    ]
