# Generated by Django 5.1.5 on 2026-07-06 23:12

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_tourbooking_applicationstage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admission',
            options={'base_manager_name': 'all_objects'},
        ),
        migrations.AlterModelManagers(
            name='admission',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='admission',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
