# Generated by Django 5.1.5 on 2026-09-23 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_admission_options_alter_admission_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentresult',
            name='student_class',
            field=models.CharField(default='KG 1', max_length=50),
        ),
        migrations.AlterField(
            model_name='tourbooking',
            name='interest_class',
            field=models.CharField(blank=True, help_text='e.g. "Nursery 1", "Primary 3"', max_length=50),
        ),
    ]
